// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claim.sql

package postgres

import (
	"context"
)

const claim = `-- name: Claim :many
with next as (
    select id
      from dbtx.inbox
     where status in ('pending', 'processing')  -- 'processing' = expired lease
       and available_at <= now()
       and attempts < max_attempts
  order by available_at, id
     limit $1
       for update SKIP LOCKED
)
   update dbtx.inbox i
      set status = 'processing'::dbtx.inbox_status,
          locked_by = $2::text,
          available_at = now()
        + interval '1 second' * $3::float8,
          attempts = i.attempts + 1,
          updated_at = now()
     from next
    where i.id = next.id
returning i.id, i.source, i.message_id, i.message_type, i.aggregate_id, i.payload, i.status, i.attempts, i.max_attempts, i.available_at, i.locked_by, i.last_error, i.received_at, i.processed_at, i.updated_at
`

type ClaimParams struct {
	Limit        int32
	LockedBy     string
	LeaseSeconds float64
}

func (q *Queries) Claim(ctx context.Context, arg ClaimParams) ([]*DbtxInbox, error) {
	rows, err := q.db.QueryContext(ctx, claim, arg.Limit, arg.LockedBy, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxInbox{}
	for rows.Next() {
		var i DbtxInbox
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MessageID,
			&i.MessageType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LastError,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
