// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"encoding/json/jsontext"
	"uuid"
)

type DbtxInboxStatus string

const (
	DbtxInboxStatusPending    DbtxInboxStatus = "pending"
	DbtxInboxStatusProcessing DbtxInboxStatus = "processing"
	DbtxInboxStatusDone       DbtxInboxStatus = "done"
	DbtxInboxStatusDead       DbtxInboxStatus = "dead"
)

func (e *DbtxInboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DbtxInboxStatus(s)
	case string:
		*e = DbtxInboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DbtxInboxStatus: %T", src)
	}
	return nil
}

type NullDbtxInboxStatus struct {
	DbtxInboxStatus DbtxInboxStatus
	Valid           bool // Valid is true if DbtxInboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDbtxInboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DbtxInboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DbtxInboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDbtxInboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DbtxInboxStatus), nil
}

func (e DbtxInboxStatus) Valid() bool {
	switch e {
	case DbtxInboxStatusPending,
		DbtxInboxStatusProcessing,
		DbtxInboxStatusDone,
		DbtxInboxStatusDead:
		return true
	}
	return false
}

func AllDbtxInboxStatusValues() []DbtxInboxStatus {
	return []DbtxInboxStatus{
		DbtxInboxStatusPending,
		DbtxInboxStatusProcessing,
		DbtxInboxStatusDone,
		DbtxInboxStatusDead,
	}
}

type DbtxInbox struct {
	ID          uuid.UUID
	Source      string
	MessageID   string
	MessageType string
	AggregateID sql.NullString
	Payload     jsontext.Value
	Status      DbtxInboxStatus
	Attempts    int32
	MaxAttempts int32
	AvailableAt time.Time
	LockedBy    sql.NullString
	LastError   sql.NullString
	ReceivedAt  time.Time
	ProcessedAt sql.NullTime
	UpdatedAt   time.Time
}
