// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nack.sql

package postgres

import (
	"context"

	"uuid"
)

const nack = `-- name: Nack :exec
update dbtx.inbox
   set status = (case when $2::bool then 'dead' else 'pending' end)::dbtx.inbox_status,
       available_at = now()
     + interval '1 second' * $3::float8,
       locked_by = null,
       last_error = $4::text,
       updated_at = now()
 where id = $1
   and locked_by = $5::text
   and status = 'processing'
`

type NackParams struct {
	ID           uuid.UUID
	Dead         bool
	DelaySeconds float64
	LastError    string
	LockedBy     string
}

func (q *Queries) Nack(ctx context.Context, arg NackParams) error {
	_, err := q.db.ExecContext(ctx, nack,
		arg.ID,
		arg.Dead,
		arg.DelaySeconds,
		arg.LastError,
		arg.LockedBy,
	)
	return err
}
