// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"uuid"
)

type Querier interface {
	Ack(ctx context.Context, arg AckParams) (int64, error)
	Claim(ctx context.Context, arg ClaimParams) ([]*DbtxInbox, error)
	// Claims the oldest unfinished message of each aggregate, so messages of the
	// same aggregate are handled one at a time, in order. Messages without an
	// aggregate are not ordered. A dead message no longer blocks the messages
	// after it.
	ClaimByAggregateID(ctx context.Context, arg ClaimByAggregateIDParams) ([]*DbtxInbox, error)
	Count(ctx context.Context) (int64, error)
	Create(ctx context.Context, arg CreateParams) (uuid.UUID, error)
	ExpireLeases(ctx context.Context) error
	Find(ctx context.Context, id uuid.UUID) (*DbtxInbox, error)
	ListDead(ctx context.Context, limit int32) ([]*DbtxInbox, error)
	Nack(ctx context.Context, arg NackParams) error
	Purge(ctx context.Context, arg PurgeParams) (int64, error)
	Requeue(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
