// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare_and_delete.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const compareAndDelete = `-- name: CompareAndDelete :one
with expired as (
  delete from dbtx.cache where dbtx.cache.key = $1 and dbtx.cache.expires_at <= statement_timestamp() returning dbtx.cache.key
),
curr as (
  select dbtx.cache.key
    from dbtx.cache
   where dbtx.cache.key = $1
     and lease is null
     and (expires_at is null or expires_at > statement_timestamp())
),
deleted as (
     delete
       from dbtx.cache
      where dbtx.cache.key = $1
        and lease is null
        and value = $2::jsonb
        and not exists (select 1 from expired)
  returning dbtx.cache.key
)
select exists (select 1 from curr) as found, exists (select 1 from deleted) as deleted
`

type CompareAndDeleteParams struct {
	Key   string
	Value jsontext.Value
}

type CompareAndDeleteRow struct {
	Found   bool
	Deleted bool
}

// curr reads the statement snapshot, so it checks liveness itself (see
// load.sql). The write re-checks its conditions against the latest row
// version, and skips rows the expired CTE deletes, so that the statement does
// not modify a row twice.
func (q *Queries) CompareAndDelete(ctx context.Context, arg CompareAndDeleteParams) (*CompareAndDeleteRow, error) {
	row := q.db.QueryRowContext(ctx, compareAndDelete, arg.Key, arg.Value)
	var i CompareAndDeleteRow
	err := row.Scan(&i.Found, &i.Deleted)
	return &i, err
}
