// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare_and_swap.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
)

const compareAndSwap = `-- name: CompareAndSwap :one
with expired as (
  delete from dbtx.cache where dbtx.cache.key = $1 and dbtx.cache.expires_at <= statement_timestamp() returning dbtx.cache.key
),
curr as (
  select dbtx.cache.key
    from dbtx.cache
   where dbtx.cache.key = $1
     and lease is null
     and (expires_at is null or expires_at > statement_timestamp())
),
swapped as (
     update dbtx.cache
        set value = $2::jsonb,
            expires_at = statement_timestamp() + $3::bigint * interval '1 microsecond',
            updated_at = statement_timestamp()
      where dbtx.cache.key = $1
        and lease is null
        and value = $4::jsonb
        and not exists (select 1 from expired)
  returning dbtx.cache.key
)
select exists (select 1 from curr) as found, exists (select 1 from swapped) as swapped
`

type CompareAndSwapParams struct {
	Key      string
	NewValue jsontext.Value
	Ttl      sql.NullInt64
	OldValue jsontext.Value
}

type CompareAndSwapRow struct {
	Found   bool
	Swapped bool
}

// curr reads the statement snapshot, so it checks liveness itself (see
// load.sql). The write re-checks its conditions against the latest row
// version, and skips rows the expired CTE deletes, so that the statement does
// not modify a row twice.
func (q *Queries) CompareAndSwap(ctx context.Context, arg CompareAndSwapParams) (*CompareAndSwapRow, error) {
	row := q.db.QueryRowContext(ctx, compareAndSwap,
		arg.Key,
		arg.NewValue,
		arg.Ttl,
		arg.OldValue,
	)
	var i CompareAndSwapRow
	err := row.Scan(&i.Found, &i.Swapped)
	return &i, err
}
