// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fulfill_lease.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
)

const fulfillLease = `-- name: FulfillLease :execrows
update dbtx.cache
   set value = $2::jsonb,
       lease = null,
       expires_at = statement_timestamp() + $3::bigint * interval '1 microsecond',
       updated_at = statement_timestamp()
 where key = $1
   and lease = $4::uuid
   and expires_at > statement_timestamp()
`

type FulfillLeaseParams struct {
	Key   string
	Value jsontext.Value
	Ttl   sql.NullInt64
	Lease string
}

// Replaces the lease placeholder with the computed value. Affects no rows if
// the lease expired, was taken over, or the key was deleted or overwritten.
func (q *Queries) FulfillLease(ctx context.Context, arg FulfillLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fulfillLease,
		arg.Key,
		arg.Value,
		arg.Ttl,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
