// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load.sql

package postgres

import (
	"context"
)

const load = `-- name: Load :one
with expired as (
  delete from dbtx.cache where key = $1 and expires_at <= statement_timestamp() returning key
)
select key, value, lease, created_at, updated_at, expires_at
  from dbtx.cache
 where dbtx.cache.key = $1
   and lease is null
   and (expires_at is null or expires_at > statement_timestamp())
`

// The select reads the statement snapshot, which still holds a row that the
// expired CTE (or a concurrent transaction) deleted, so it checks liveness
// itself instead of relying on the delete.
func (q *Queries) Load(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, load, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Lease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
