// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_or_store.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"encoding/json/jsontext"
)

const loadOrStore = `-- name: LoadOrStore :one
with ins as (
  insert into dbtx.cache as c(key, value, lease, expires_at)
       values ($1, $2::jsonb, $3::uuid, statement_timestamp() + $4::bigint * interval '1 microsecond')
  on conflict (key) do
       update
          set value = excluded.value,
              lease = excluded.lease,
              expires_at = excluded.expires_at,
              created_at = statement_timestamp(),
              updated_at = statement_timestamp()
        where c.expires_at is not null
          and c.expires_at <= statement_timestamp()  -- only overwrite if the existing row is expired
    returning key, value, lease, created_at, updated_at, expires_at
)
select key, value, lease, created_at, updated_at, expires_at, false as loaded
  from ins
union all
select key, value, lease, created_at, updated_at, expires_at, true as loaded
  from (
         select key, value, lease, created_at, updated_at, expires_at
           from dbtx.cache
          where key = $1
            and (expires_at is null or expires_at > statement_timestamp())
            and not exists (select 1 from ins)
            for share
       ) curr
`

type LoadOrStoreParams struct {
	Key   string
	Value jsontext.Value
	Lease sql.NullString
	Ttl   sql.NullInt64
}

type LoadOrStoreRow struct {
	Key       string
	Value     jsontext.Value
	Lease     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
	Loaded    bool
}

// Stores the value (or a lease placeholder) unless a live row exists, in which
// case the live row is returned with loaded = true. The caller must check the
// returned lease to tell a computed value from an in-flight placeholder.
//
// The fallback select locks the row, so that it returns the latest committed
// version (the one the conflict check saw) instead of the one in the snapshot.
// It returns no rows when the key was inserted, or an expired row replaced,
// after the snapshot was taken; the caller should retry.
func (q *Queries) LoadOrStore(ctx context.Context, arg LoadOrStoreParams) (*LoadOrStoreRow, error) {
	row := q.db.QueryRowContext(ctx, loadOrStore,
		arg.Key,
		arg.Value,
		arg.Lease,
		arg.Ttl,
	)
	var i LoadOrStoreRow
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Lease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Loaded,
	)
	return &i, err
}
