// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"

	"encoding/json/jsontext"
)

type DbtxCache struct {
	Key       string
	Value     jsontext.Value
	Lease     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}

type DbtxLiveCache struct {
	Key       string
	Value     jsontext.Value
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}
