// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release_lease.sql

package postgres

import (
	"context"
)

const releaseLease = `-- name: ReleaseLease :execrows
delete from dbtx.cache where key = $1 and lease = $2::uuid
`

type ReleaseLeaseParams struct {
	Key   string
	Lease string
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseLease, arg.Key, arg.Lease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
