// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: renew_lease.sql

package postgres

import (
	"context"
	"database/sql"
)

const renewLease = `-- name: RenewLease :execrows
update dbtx.cache
   set expires_at = statement_timestamp() + $2::bigint * interval '1 microsecond',
       updated_at = statement_timestamp()
 where key = $1
   and lease = $3::uuid
   and expires_at > statement_timestamp()
`

type RenewLeaseParams struct {
	Key   string
	Ttl   sql.NullInt64
	Lease string
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewLease, arg.Key, arg.Ttl, arg.Lease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
