// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ack.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const ack = `-- name: Ack :one
   update dbtx.idempotency_keys
      set status = 'completed',
          response = $1::jsonb,
          lease_owner = null,
          lease_expires_at = null,
          retry_after = null,
          completed_at = clock_timestamp(),
          expires_at = greatest(
            expires_at,
            clock_timestamp()
          + interval '1 second' * $2::float8
          ),
          updated_at = clock_timestamp()
    where idempotency_key = $3::text
      and fencing_token = $4::bigint
      and status = 'in_progress'
returning fencing_token
`

type AckParams struct {
	Response       jsontext.Value
	TtlSeconds     float64
	IdempotencyKey string
	FencingToken   int64
}

func (q *Queries) Ack(ctx context.Context, arg AckParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, ack,
		arg.Response,
		arg.TtlSeconds,
		arg.IdempotencyKey,
		arg.FencingToken,
	)
	var fencing_token int64
	err := row.Scan(&fencing_token)
	return fencing_token, err
}
