// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoint.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const checkpoint = `-- name: Checkpoint :one
   update dbtx.idempotency_keys
      set checkpoint_logs =
          (
            select coalesce(jsonb_agg(log.entry order by log.n), '[]')
              from jsonb_array_elements(
                     checkpoint_logs
                  || jsonb_build_array(
                       jsonb_build_object('name', checkpoint, 'data', checkpoint_data)
                     )
                   ) with ordinality as log(entry, n)
             where log.n > jsonb_array_length(checkpoint_logs) + 1 - 100
          ),
          checkpoint = $1::text,
          checkpoint_data = $2::jsonb,
          updated_at = now(),
          lease_expires_at = clock_timestamp()
        + interval '1 second' * $3::float8
    where idempotency_key = $4::text
      and fencing_token = $5::bigint
      and status = 'in_progress'
returning checkpoint
`

type CheckpointParams struct {
	Checkpoint     string
	CheckpointData jsontext.Value
	LeaseSeconds   float64
	IdempotencyKey string
	FencingToken   int64
}

// Extends the lease on commit, so a Claim blocked on the row lock does not
// take over between steps. The previous checkpoint is appended to
// checkpoint_logs, which keeps the last 100 entries, so that a long or
// looping run does not rewrite an ever larger value on every step.
func (q *Queries) Checkpoint(ctx context.Context, arg CheckpointParams) (string, error) {
	row := q.db.QueryRowContext(ctx, checkpoint,
		arg.Checkpoint,
		arg.CheckpointData,
		arg.LeaseSeconds,
		arg.IdempotencyKey,
		arg.FencingToken,
	)
	var checkpoint string
	err := row.Scan(&checkpoint)
	return checkpoint, err
}
