// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fail.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const fail = `-- name: Fail :one
   update dbtx.idempotency_keys
      set status = 'failed',
          response = $1::jsonb,
          error = $2::text,
          lease_owner = null,
          lease_expires_at = null,
          retry_after = null,
          completed_at = clock_timestamp(),
          expires_at = greatest(
            expires_at,
            clock_timestamp()
          + interval '1 second' * $3::float8
          ),
          updated_at = clock_timestamp()
    where idempotency_key = $4::text
      and fencing_token = $5::bigint
      and status = 'in_progress'
returning fencing_token
`

type FailParams struct {
	Response       jsontext.Value
	Error          string
	TtlSeconds     float64
	IdempotencyKey string
	FencingToken   int64
}

func (q *Queries) Fail(ctx context.Context, arg FailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, fail,
		arg.Response,
		arg.Error,
		arg.TtlSeconds,
		arg.IdempotencyKey,
		arg.FencingToken,
	)
	var fencing_token int64
	err := row.Scan(&fencing_token)
	return fencing_token, err
}
