// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fail.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const fail = `-- name: Fail :one
   update dbtx.idempotency_keys
      set status = 'failed',
          response = $1::jsonb,
          error = $2::text,
          lease_owner = null,
          lease_expires_at = null,
          retry_after = null,
          completed_at = clock_timestamp(),
          expires_at = greatest(
            expires_at,
            clock_timestamp()
          + interval '1 second' * $3::float8
          ),
          updated_at = clock_timestamp()
    where idempotency_key = $4::text
      and fencing_token = $5::bigint
      and status = 'in_progress'
returning idempotency_key, request, status, fencing_token, lease_owner, lease_expires_at, attempts, checkpoint, checkpoint_data, checkpoint_logs, response, error, created_at, updated_at, completed_at, retry_after, expires_at
`

type FailParams struct {
	Response       jsontext.Value
	Error          string
	TtlSeconds     float64
	IdempotencyKey string
	FencingToken   int64
}

func (q *Queries) Fail(ctx context.Context, arg FailParams) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, fail,
		arg.Response,
		arg.Error,
		arg.TtlSeconds,
		arg.IdempotencyKey,
		arg.FencingToken,
	)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.Request,
		&i.Status,
		&i.FencingToken,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.CheckpointLogs,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RetryAfter,
		&i.ExpiresAt,
	)
	return &i, err
}
