// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nack.sql

package postgres

import (
	"context"
)

const nack = `-- name: Nack :one
   update dbtx.idempotency_keys
      set status = (
  case
       when attempts >= $1::int
       then 'failed'
       else 'retryable'
  end)::dbtx.idempotency_key_status,
          error = $2::text,
          lease_owner = null,
          lease_expires_at = null,
          retry_after = case
                             when attempts >= $1::int
                                  or $3::float8 <= 0
                                  or $4::float8 <= 0
                             then null
                             else clock_timestamp() + interval '1 second' * case
                                    when $4::float8 >= $3::float8
                                    then $3::float8
                                    else least(
                                      $3::float8,
                                      $4::float8
                                        * power(2::float8, least(
                                            attempts - 1,
                                            ceil(log(2::numeric, $3::numeric / $4::numeric)
                                          )::int)::float8)
                                    )
                                  end
                        end,
          completed_at = case
                              when attempts >= $1::int
                              then clock_timestamp()
                         end,
          expires_at = greatest(
            expires_at,
            clock_timestamp()
          + interval '1 second' * $5::float8
          ),
          updated_at = clock_timestamp()
    where idempotency_key = $6::text
      and fencing_token = $7::bigint
      and status = 'in_progress'
returning fencing_token
`

type NackParams struct {
	MaxAttempts        int32
	Error              string
	MaxBackoffSeconds  float64
	BaseBackoffSeconds float64
	TtlSeconds         float64
	IdempotencyKey     string
	FencingToken       int64
}

// Exponential backoff: base * 2^(attempts-1), capped. `attempts` is the old
// row value, i.e. the attempt that just failed. Terminal when exhausted.
func (q *Queries) Nack(ctx context.Context, arg NackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nack,
		arg.MaxAttempts,
		arg.Error,
		arg.MaxBackoffSeconds,
		arg.BaseBackoffSeconds,
		arg.TtlSeconds,
		arg.IdempotencyKey,
		arg.FencingToken,
	)
	var fencing_token int64
	err := row.Scan(&fencing_token)
	return fencing_token, err
}
