// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package postgres

import (
	"context"
)

const purge = `-- name: Purge :execrows
delete
  from dbtx.idempotency_keys
 where ctid in
            (
              select ctid
                from dbtx.idempotency_keys
               where expires_at < now()
                 and (status <> 'in_progress' or lease_expires_at < now())
               limit 1000
                 for update SKIP LOCKED
            )
`

func (q *Queries) Purge(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
