// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claim_aggregate.sql

package postgres

import (
	"context"
)

const claimByAggregateID = `-- name: ClaimByAggregateID :many
with next as (
    select i.id
      from dbtx.inbox i
     where i.status in ('pending', 'processing')
       and i.available_at <= now()
       and i.attempts < i.max_attempts
       and not exists
           (
             select 1
               from dbtx.inbox earlier
              where earlier.aggregate_id = i.aggregate_id
                and earlier.id < i.id
                and earlier.status in ('pending', 'processing')
           )
       and not exists
           (
             select 1
               from dbtx.inbox busy
              where busy.aggregate_id = i.aggregate_id
                and busy.id <> i.id
                and busy.status = 'processing'
                and busy.available_at > now()
           )
  order by i.available_at, i.id
     limit $1
       for update SKIP LOCKED
)
   update dbtx.inbox i
      set status = 'processing'::dbtx.inbox_status,
          locked_by = $2::text,
          available_at = now()
        + interval '1 second' * $3::float8,
          attempts = i.attempts + 1,
          updated_at = now()
     from next
    where i.id = next.id
returning i.id, i.source, i.message_id, i.message_type, i.aggregate_id, i.payload, i.status, i.attempts, i.max_attempts, i.available_at, i.locked_by, i.last_error, i.received_at, i.processed_at, i.updated_at
`

type ClaimByAggregateIDParams struct {
	Limit        int32
	LockedBy     string
	LeaseSeconds float64
}

// Claims the oldest unfinished message of each aggregate, so messages of the
// same aggregate are handled one at a time, in order. Messages without an
// aggregate are not ordered. A dead message no longer blocks the messages
// after it.
//
// A message is also skipped while another message of its aggregate holds a
// live lease, whatever their order: an earlier message can become pending
// after a later one was claimed, when it is requeued or when the transaction
// that enqueued it commits late.
func (q *Queries) ClaimByAggregateID(ctx context.Context, arg ClaimByAggregateIDParams) ([]*DbtxInbox, error) {
	rows, err := q.db.QueryContext(ctx, claimByAggregateID, arg.Limit, arg.LockedBy, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxInbox{}
	for rows.Next() {
		var i DbtxInbox
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MessageID,
			&i.MessageType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LastError,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
