// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
	"uuid"
)

const create = `-- name: Create :one
insert into dbtx.inbox(source, message_id, message_type, aggregate_id,
                       payload, available_at, max_attempts)
     values ($1, $2, $3, nullif($5::text, ''), $4,
             coalesce($6::timestamptz, now()),
             coalesce($7::int, 10))
on conflict (source, message_id) do nothing
  returning id
`

type CreateParams struct {
	Source      string
	MessageID   string
	MessageType string
	Payload     jsontext.Value
	AggregateID string
	AvailableAt sql.NullTime
	MaxAttempts sql.NullInt32
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.Source,
		arg.MessageID,
		arg.MessageType,
		arg.Payload,
		arg.AggregateID,
		arg.AvailableAt,
		arg.MaxAttempts,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
