// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expire_leases.sql

package postgres

import (
	"context"
)

const expireLeases = `-- name: ExpireLeases :exec
with expired as (
    select id
      from dbtx.inbox
     where status = 'processing'
       and available_at <= now()
       and attempts >= max_attempts
       for update skip locked
)
update dbtx.inbox i
   set status = 'dead'::dbtx.inbox_status,
       locked_by = null,
       last_error = 'lease expired on final attempt',
       updated_at = now()
  from expired
 where i.id = expired.id
`

// Marks messages whose lease expired on their final attempt as dead.
//
// Rows locked by a running handler are skipped instead of waited for: the
// handler is still delivering the message. Skipping also means concurrent
// calls never wait on each other, so they cannot deadlock.
func (q *Queries) ExpireLeases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireLeases)
	return err
}
