// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expire_leases.sql

package postgres

import (
	"context"
)

const expireLeases = `-- name: ExpireLeases :exec
update dbtx.inbox
   set status = 'dead'::dbtx.inbox_status,
       locked_by = null,
       last_error = 'lease expired on final attempt',
       updated_at = now()
 where status = 'processing'
   and available_at <= now()
   and attempts >= max_attempts
`

func (q *Queries) ExpireLeases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireLeases)
	return err
}
