// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find.sql

package postgres

import (
	"context"

	"uuid"
)

const find = `-- name: Find :one
select id, source, message_id, message_type, aggregate_id, payload, status, attempts, max_attempts, available_at, locked_by, last_error, received_at, processed_at, updated_at from dbtx.inbox where id = $1
`

func (q *Queries) Find(ctx context.Context, id uuid.UUID) (*DbtxInbox, error) {
	row := q.db.QueryRowContext(ctx, find, id)
	var i DbtxInbox
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.MessageID,
		&i.MessageType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
