// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_dead.sql

package postgres

import (
	"context"
)

const listDead = `-- name: ListDead :many
  select id, source, message_id, message_type, aggregate_id, payload, status, attempts, max_attempts, available_at, locked_by, last_error, received_at, processed_at, updated_at
    from dbtx.inbox
   where status = 'dead'
order by updated_at, id
   limit $1
`

func (q *Queries) ListDead(ctx context.Context, limit int32) ([]*DbtxInbox, error) {
	rows, err := q.db.QueryContext(ctx, listDead, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxInbox{}
	for rows.Next() {
		var i DbtxInbox
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.MessageID,
			&i.MessageType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LastError,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
