// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock_aggregate.sql

package postgres

import (
	"context"
)

const lockAggregate = `-- name: LockAggregate :exec
select pg_advisory_xact_lock(hashtext('dbtx.inbox'), hashtext($1::text))
`

// Serialises the handlers of an aggregate until the transaction ends. Claim
// already skips aggregates with a live lease; this also covers a handler that
// is still running after its lease expired. The two-key form keeps the lock
// apart from other advisory locks of the application.
func (q *Queries) LockAggregate(ctx context.Context, aggregateID string) error {
	_, err := q.db.ExecContext(ctx, lockAggregate, aggregateID)
	return err
}
