// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"uuid"
)

type Querier interface {
	Ack(ctx context.Context, arg AckParams) (int64, error)
	Claim(ctx context.Context, arg ClaimParams) ([]*DbtxInbox, error)
	// Claims the oldest unfinished message of each aggregate, so messages of the
	// same aggregate are handled one at a time, in order. Messages without an
	// aggregate are not ordered. A dead message no longer blocks the messages
	// after it.
	//
	// A message is also skipped while another message of its aggregate holds a
	// live lease, whatever their order: an earlier message can become pending
	// after a later one was claimed, when it is requeued or when the transaction
	// that enqueued it commits late.
	ClaimByAggregateID(ctx context.Context, arg ClaimByAggregateIDParams) ([]*DbtxInbox, error)
	Count(ctx context.Context) (int64, error)
	Create(ctx context.Context, arg CreateParams) (uuid.UUID, error)
	// Marks messages whose lease expired on their final attempt as dead.
	//
	// Rows locked by a running handler are skipped instead of waited for: the
	// handler is still delivering the message. Skipping also means concurrent
	// calls never wait on each other, so they cannot deadlock.
	ExpireLeases(ctx context.Context) error
	Find(ctx context.Context, id uuid.UUID) (*DbtxInbox, error)
	ListDead(ctx context.Context, limit int32) ([]*DbtxInbox, error)
	// Renews the lease of a message leased to locked_by, and locks its row until
	// the handler's transaction ends. Claim skips locked rows, and ExpireLeases
	// waits for them, so the message is not delivered again while it is being
	// handled, even if the lease expires meanwhile.
	Lock(ctx context.Context, arg LockParams) (int64, error)
	// Serialises the handlers of an aggregate until the transaction ends. Claim
	// already skips aggregates with a live lease; this also covers a handler that
	// is still running after its lease expired. The two-key form keeps the lock
	// apart from other advisory locks of the application.
	LockAggregate(ctx context.Context, aggregateID string) error
	Nack(ctx context.Context, arg NackParams) (int64, error)
	Purge(ctx context.Context, arg PurgeParams) (int64, error)
	// Returns a leased message that was never handled, and refunds its attempt.
	Release(ctx context.Context, arg ReleaseParams) (int64, error)
	Requeue(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
