// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release.sql

package postgres

import (
	"context"

	"uuid"
)

const release = `-- name: Release :execrows
update dbtx.inbox
   set status = 'pending'::dbtx.inbox_status,
       attempts = attempts - 1,
       locked_by = null,
       available_at = now(),
       updated_at = now()
 where id = $1::uuid
   and locked_by = $2::text
   and status = 'processing'
`

type ReleaseParams struct {
	ID       uuid.UUID
	LockedBy string
}

// Returns a leased message that was never handled, and refunds its attempt.
func (q *Queries) Release(ctx context.Context, arg ReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, release, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
