// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ack.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const ack = `-- name: Ack :one
   update dbtx.idempotency_keys
      set status = 'completed',
          response = $3,
          lease_owner = null,
          lease_expires_at = null,
          completed_at = now(),
          updated_at = now()
    where idempotency_key = $1
      and fencing_token = $2
      and status = 'in_progress'
returning idempotency_key, request, status, fencing_token, lease_owner, lease_expires_at, attempts, checkpoint, checkpoint_data, checkpoint_logs, response, error, created_at, updated_at, completed_at, expires_at
`

type AckParams struct {
	IdempotencyKey string
	FencingToken   int64
	Response       jsontext.Value
}

func (q *Queries) Ack(ctx context.Context, arg AckParams) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, ack, arg.IdempotencyKey, arg.FencingToken, arg.Response)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.Request,
		&i.Status,
		&i.FencingToken,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.CheckpointLogs,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
