// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claim.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const claim = `-- name: Claim :one
insert into dbtx.idempotency_keys as ik(idempotency_key, request, status,
                                        fencing_token, lease_owner,
                                        lease_expires_at, attempts)
     values ($1::text, $2::jsonb,
             'in_progress', 1, $3::text,
             now() + interval '1 second' * $4::float8, 1)
on conflict (idempotency_key) do
     update
        set status = 'in_progress',
            fencing_token = ik.fencing_token + 1,
            lease_owner = EXCLUDED.lease_owner,
            lease_expires_at = EXCLUDED.lease_expires_at,
            attempts = ik.attempts + 1,
            error = null,
            updated_at = now()
      where ik.request = EXCLUDED.request
        and ik.attempts < $5::int
        and ((ik.status = 'in_progress' and ik.lease_expires_at <= now()) or ik.status = 'retryable')
  returning fencing_token,
            attempts,
            checkpoint,  -- resume from here on takeover
            checkpoint_data,
            (xmax = 0) as is_new
`

type ClaimParams struct {
	IdempotencyKey string
	Request        jsontext.Value
	LeaseOwner     string
	LeaseSeconds   float64
	MaxAttempts    int32
}

type ClaimRow struct {
	FencingToken   int64
	Attempts       int32
	Checkpoint     string
	CheckpointData jsontext.Value
	IsNew          bool
}

func (q *Queries) Claim(ctx context.Context, arg ClaimParams) (*ClaimRow, error) {
	row := q.db.QueryRowContext(ctx, claim,
		arg.IdempotencyKey,
		arg.Request,
		arg.LeaseOwner,
		arg.LeaseSeconds,
		arg.MaxAttempts,
	)
	var i ClaimRow
	err := row.Scan(
		&i.FencingToken,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.IsNew,
	)
	return &i, err
}
