// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claim.sql

package postgres

import (
	"context"
	"time"

	"encoding/json/jsontext"
)

const claim = `-- name: Claim :one
select outcome::text,
       coalesce(fencing_token, 0)::bigint as fencing_token,
       coalesce(attempts, 0)::int as attempts,
       coalesce(checkpoint, '')::text as checkpoint,
       coalesce(checkpoint_data, 'null')::jsonb as checkpoint_data,
       coalesce(response, 'null')::jsonb as response,
       coalesce(error, '')::text as error,
       coalesce(lease_expires_at, '0001-01-01 00:00:00+00')::timestamptz as lease_expires_at,
       coalesce(retry_after, '0001-01-01 00:00:00+00')::timestamptz as retry_after
  from dbtx.claim(
         $1::text, $2::jsonb,
         $3::text, $4::float8,
         $5::int, $6::float8
       )
`

type ClaimParams struct {
	IdempotencyKey string
	Request        jsontext.Value
	LeaseOwner     string
	LeaseSeconds   float64
	MaxAttempts    int32
	TtlSeconds     float64
}

type ClaimRow struct {
	Outcome        string
	FencingToken   int64
	Attempts       int32
	Checkpoint     string
	CheckpointData jsontext.Value
	Response       jsontext.Value
	Error          string
	LeaseExpiresAt time.Time
	RetryAfter     time.Time
}

// Columns that do not apply to the outcome are null; they are coalesced to
// the Go zero values ('0001-01-01' scans to time.Time{}).
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) (*ClaimRow, error) {
	row := q.db.QueryRowContext(ctx, claim,
		arg.IdempotencyKey,
		arg.Request,
		arg.LeaseOwner,
		arg.LeaseSeconds,
		arg.MaxAttempts,
		arg.TtlSeconds,
	)
	var i ClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.FencingToken,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.Response,
		&i.Error,
		&i.LeaseExpiresAt,
		&i.RetryAfter,
	)
	return &i, err
}
