// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package postgres

import (
	"context"
)

const delete = `-- name: Delete :one
delete from dbtx.idempotency_keys where key = $1 returning key, request, response, created_at
`

func (q *Queries) Delete(ctx context.Context, key string) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, delete, key)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Request,
		&i.Response,
		&i.CreatedAt,
	)
	return &i, err
}
