// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package postgres

import (
	"context"
)

const delete = `-- name: Delete :one
delete from dbtx.idempotency_keys where scope = $1 and key = $2 returning scope, key, request, response, created_at
`

type DeleteParams struct {
	Scope string
	Key   string
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, delete, arg.Scope, arg.Key)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.Request,
		&i.Response,
		&i.CreatedAt,
	)
	return &i, err
}
