// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_before.sql

package postgres

import (
	"context"
	"time"
)

const deleteBefore = `-- name: DeleteBefore :execrows
delete from dbtx.idempotency_keys where created_at < $1
`

func (q *Queries) DeleteBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
