// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fail.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
)

const fail = `-- name: Fail :one
   update dbtx.idempotency_keys
      set status = 'failed',
          response = $3,
          error = $4::text,
          lease_owner = null,
          lease_expires_at = null,
          completed_at = now(),
          updated_at = now()
    where idempotency_key = $1
      and fencing_token = $2
      and status = 'in_progress'
returning idempotency_key, request, status, fencing_token, lease_owner, lease_expires_at, attempts, checkpoint, checkpoint_data, checkpoint_logs, response, error, created_at, updated_at, completed_at, expires_at
`

type FailParams struct {
	IdempotencyKey string
	FencingToken   int64
	Response       jsontext.Value
	Error          string
}

func (q *Queries) Fail(ctx context.Context, arg FailParams) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, fail,
		arg.IdempotencyKey,
		arg.FencingToken,
		arg.Response,
		arg.Error,
	)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.Request,
		&i.Status,
		&i.FencingToken,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.CheckpointLogs,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
