// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspect.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
)

const inspect = `-- name: Inspect :one
select status,
       response,
       error,
       lease_expires_at,
       attempts,
       coalesce(status = 'in_progress' and lease_expires_at <= now(), false)::bool as lease_expired,
       (request <> $1::jsonb) as payload_mismatch
  from dbtx.idempotency_keys
 where idempotency_key = $2::text
`

type InspectParams struct {
	Request        jsontext.Value
	IdempotencyKey string
}

type InspectRow struct {
	Status          DbtxIdempotencyKeyStatus
	Response        jsontext.Value
	Error           sql.NullString
	LeaseExpiresAt  sql.NullTime
	Attempts        int32
	LeaseExpired    bool
	PayloadMismatch bool
}

// Called only when Claim returned no rows.
func (q *Queries) Inspect(ctx context.Context, arg InspectParams) (*InspectRow, error) {
	row := q.db.QueryRowContext(ctx, inspect, arg.Request, arg.IdempotencyKey)
	var i InspectRow
	err := row.Scan(
		&i.Status,
		&i.Response,
		&i.Error,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LeaseExpired,
		&i.PayloadMismatch,
	)
	return &i, err
}
