// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock.sql

package postgres

import (
	"context"
)

const lock = `-- name: Lock :one
   update dbtx.idempotency_keys
      set lease_expires_at = now()
        + interval '1 second' * $1::float8,
          updated_at = now()
    where idempotency_key = $2::text
      and fencing_token = $3::bigint
      and status = 'in_progress'
returning fencing_token
`

type LockParams struct {
	LeaseSeconds   float64
	IdempotencyKey string
	FencingToken   int64
}

// Locks the row for the duration of the step transaction and extends the
// lease. While the row is locked, a concurrent Claim blocks until commit, so
// no separate heartbeat is needed.
func (q *Queries) Lock(ctx context.Context, arg LockParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lock, arg.LeaseSeconds, arg.IdempotencyKey, arg.FencingToken)
	var fencing_token int64
	err := row.Scan(&fencing_token)
	return fencing_token, err
}
