// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"encoding/json"
	"time"
)

type DbtxIdempotencyKey struct {
	Scope     string
	Key       string
	Request   json.RawMessage
	Response  json.RawMessage
	CreatedAt time.Time
}
