// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nack.sql

package postgres

import (
	"context"
)

const nack = `-- name: Nack :one
   update dbtx.idempotency_keys
      set status = 'retryable',
          error = $3::text,
          lease_owner = null,
          lease_expires_at = null,
          updated_at = now()
    where idempotency_key = $1
      and fencing_token = $2
      and status = 'in_progress'
returning idempotency_key, request, status, fencing_token, lease_owner, lease_expires_at, attempts, checkpoint, checkpoint_data, checkpoint_logs, response, error, created_at, updated_at, completed_at, expires_at
`

type NackParams struct {
	IdempotencyKey string
	FencingToken   int64
	Error          string
}

func (q *Queries) Nack(ctx context.Context, arg NackParams) (*DbtxIdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, nack, arg.IdempotencyKey, arg.FencingToken, arg.Error)
	var i DbtxIdempotencyKey
	err := row.Scan(
		&i.IdempotencyKey,
		&i.Request,
		&i.Status,
		&i.FencingToken,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.Checkpoint,
		&i.CheckpointData,
		&i.CheckpointLogs,
		&i.Response,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
