// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update.sql

package postgres

import (
	"context"
	"encoding/json"
)

const update = `-- name: Update :exec
update dbtx.idempotency_keys set request = $1, response = $2 where key = $3
`

type UpdateParams struct {
	Request  json.RawMessage
	Response json.RawMessage
	Key      string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update, arg.Request, arg.Response, arg.Key)
	return err
}
