// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update.sql

package postgres

import (
	"context"
	"encoding/json"
)

const update = `-- name: Update :exec
update dbtx.idempotency_keys set response = $1 where scope = $2 and key = $3
`

type UpdateParams struct {
	Response json.RawMessage
	Scope    string
	Key      string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update, arg.Response, arg.Scope, arg.Key)
	return err
}
