// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_dead.sql

package postgres

import (
	"context"
)

const listDead = `-- name: ListDead :many
  select id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_by, last_error, created_at, updated_at, processed_at
    from dbtx.outbox
   where status = 'dead'
order by updated_at, id
   limit $1
`

func (q *Queries) ListDead(ctx context.Context, limit int32) ([]*DbtxOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listDead, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxOutbox{}
	for rows.Next() {
		var i DbtxOutbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
