// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock.sql

package postgres

import (
	"context"

	"uuid"
)

const lock = `-- name: Lock :execrows
update dbtx.outbox
   set available_at = now()
     + interval '1 second' * $1::float8,
       updated_at = now()
 where id = $2
   and locked_by = $3::text
   and status = 'processing'
`

type LockParams struct {
	LeaseSeconds float64
	ID           uuid.UUID
	LockedBy     string
}

// Renews the lease of a message leased to locked_by, and locks its row until
// the handler's transaction ends. Poll skips locked rows, and Dead waits for
// them, so the message is not delivered again while it is being handled, even
// if the lease expires meanwhile.
func (q *Queries) Lock(ctx context.Context, arg LockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lock, arg.LeaseSeconds, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
