// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"uuid"
)

type Querier interface {
	Ack(ctx context.Context, arg AckParams) (int64, error)
	Count(ctx context.Context) (int64, error)
	Create(ctx context.Context, arg CreateParams) (uuid.UUID, error)
	// Dead marks messages whose lease expired on their final attempt, for
	// example because the worker crashed, as dead.
	//
	// Rows locked by a running handler are skipped instead of waited for: the
	// handler is still delivering the message. Skipping also means concurrent
	// calls never wait on each other, so they cannot deadlock.
	Dead(ctx context.Context) (int64, error)
	Find(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error)
	ListDead(ctx context.Context, limit int32) ([]*DbtxOutbox, error)
	// Renews the lease of a message leased to locked_by, and locks its row until
	// the handler's transaction ends. Poll skips locked rows, and Dead waits for
	// them, so the message is not delivered again while it is being handled, even
	// if the lease expires meanwhile.
	Lock(ctx context.Context, arg LockParams) (int64, error)
	Nack(ctx context.Context, arg NackParams) (int64, error)
	Poll(ctx context.Context, arg PollParams) ([]*DbtxOutbox, error)
	Purge(ctx context.Context, arg PurgeParams) (int64, error)
	// Returns a leased message that was never handled, and refunds its attempt.
	Release(ctx context.Context, arg ReleaseParams) (int64, error)
	Requeue(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
