// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requeue.sql

package postgres

import (
	"context"

	"uuid"
)

const requeue = `-- name: Requeue :execrows
update dbtx.outbox
   set status = 'pending'::dbtx.outbox_status,
       attempts = 0,
       available_at = now(),
       locked_by = null,
       last_error = null,
       updated_at = now()
 where id = $1
   and status = 'dead'
`

func (q *Queries) Requeue(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
