// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ack.sql

package postgres

import (
	"context"
	"database/sql"

	"uuid"
)

const ack = `-- name: Ack :execrows
update dbtx.outbox
   set status = 'done',
       processed_at = now(),
       locked_by = null,
       last_error = null,
       updated_at = now()
 where id = $1
   and locked_by = $2
   and status = 'processing'
`

type AckParams struct {
	ID       uuid.UUID
	LockedBy sql.NullString
}

func (q *Queries) Ack(ctx context.Context, arg AckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ack, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
