// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: count.sql

package postgres

import (
	"context"
)

const count = `-- name: Count :one
select count(*) from dbtx.outbox where retry_at is null or retry_at <= now()
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}
