// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: count_dlq.sql

package postgres

import (
	"context"
)

const countDLQ = `-- name: CountDLQ :one
select count(*) from dbtx.outbox_dlq
`

func (q *Queries) CountDLQ(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDLQ)
	var count int64
	err := row.Scan(&count)
	return count, err
}
