// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
	"uuid"
)

const create = `-- name: Create :one
insert into dbtx.outbox(aggregate_id, aggregate_type, event_type, payload,
                        max_attempts, available_at)
     values ($1, $2,
             $3, $4,
             coalesce($5::int, 10),
             coalesce($6::timestamptz, now()))
  returning id
`

type CreateParams struct {
	AggregateID   string
	AggregateType string
	EventType     string
	Payload       jsontext.Value
	MaxAttempts   sql.NullInt32
	AvailableAt   sql.NullTime
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.MaxAttempts,
		arg.AvailableAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
