// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create.sql

package postgres

import (
	"context"
	"encoding/json"
	"time"
)

const create = `-- name: Create :one
insert into dbtx.outbox(aggregate_id, aggregate_type, type, payload,
                        max_retry, visible_at)
     values ($1, $2, $3, $4, $5, $6)
  returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
`

type CreateParams struct {
	AggregateID   string
	AggregateType string
	Type          string
	Payload       json.RawMessage
	MaxRetry      int32
	VisibleAt     time.Time
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.AggregateID,
		arg.AggregateType,
		arg.Type,
		arg.Payload,
		arg.MaxRetry,
		arg.VisibleAt,
	)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
