// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dead.sql

package postgres

import (
	"context"
)

const dead = `-- name: Dead :execrows
update dbtx.outbox
   set status = 'dead'::dbtx.outbox_status,
       locked_by = null,
       last_error = 'lease expired on final attempt',
       updated_at = now()
 where status = 'processing'
   and available_at <= now()
   and attempts >= max_attempts
`

// Dead marks messages whose lease expired on their final attempt, for
// example because the worker crashed, as dead.
func (q *Queries) Dead(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, dead)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
