// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package postgres

import (
	"context"

	"uuid"
)

const delete = `-- name: Delete :one
delete from dbtx.outbox where id = $1 returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, failure_reason, retry_at, retry_count, run_at
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, delete, id)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.RetryAt,
		&i.RetryCount,
		&i.RunAt,
	)
	return &i, err
}
