// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dequeue.sql

package postgres

import (
	"context"

	"uuid"
)

const dequeue = `-- name: Dequeue :one
with locked as (
    select o.id as locked_id
      from dbtx.outbox o
     where o.id = $1
       and (retry_at is null or retry_at <= now())
     limit 1 for
    update SKIP LOCKED
)
   update dbtx.outbox o
      set updated_at = now(), run_at = now(), retry_count = o.retry_count + 1
     from locked l
    where o.id = l.locked_id
returning o.id, o.aggregate_id, o.aggregate_type, o.type, o.payload, o.created_at, o.updated_at, o.failure_reason, o.retry_at, o.retry_count, o.run_at
`

func (q *Queries) Dequeue(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, dequeue, id)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.RetryAt,
		&i.RetryCount,
		&i.RunAt,
	)
	return &i, err
}
