// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enqueue.sql

package postgres

import (
	"context"
	"encoding/json"

	"uuid"
)

const enqueue = `-- name: Enqueue :one
insert into dbtx.outbox(aggregate_id, aggregate_type, type, payload)
     values ($1, $2, $3, $4)
  returning id
`

type EnqueueParams struct {
	AggregateID   string
	AggregateType string
	Type          string
	Payload       json.RawMessage
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, enqueue,
		arg.AggregateID,
		arg.AggregateType,
		arg.Type,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
