// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enqueue_dlq.sql

package postgres

import (
	"context"

	"uuid"
)

const enqueueDLQ = `-- name: EnqueueDLQ :one
with deleted as (
  delete from dbtx.outbox o where o.id = $1 returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, failure_reason, retry_at, retry_count, run_at
)
insert into dbtx.outbox_dlq(id, aggregate_id, aggregate_type, type, payload, created_at, failure_reason, retry_at, retry_count, run_at)
     select id,
            aggregate_id,
            aggregate_type,
            type,
            payload,
            created_at,
            failure_reason,
            retry_at,
            retry_count,
            run_at
       from deleted
  returning id, aggregate_id, aggregate_type, type, payload, created_at, failure_reason, retry_at, retry_count, run_at
`

func (q *Queries) EnqueueDLQ(ctx context.Context, id uuid.UUID) (*DbtxOutboxDlq, error) {
	row := q.db.QueryRowContext(ctx, enqueueDLQ, id)
	var i DbtxOutboxDlq
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.FailureReason,
		&i.RetryAt,
		&i.RetryCount,
		&i.RunAt,
	)
	return &i, err
}
