// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find.sql

package postgres

import (
	"context"

	"uuid"
)

const exists = `-- name: Exists :one
select exists(select 1 from dbtx.outbox o where o.id = $1)
`

func (q *Queries) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, exists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const find = `-- name: Find :one
select id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at from dbtx.outbox o where o.id = $1 for update SKIP LOCKED
`

func (q *Queries) Find(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, find, id)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
