// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find.sql

package postgres

import (
	"context"

	"uuid"
)

const find = `-- name: Find :one
with locked as (
  select id as locked_id
    from dbtx.outbox o
   where o.id = $1 for update SKIP LOCKED
)
   update dbtx.outbox o
      set retry_count = retry_count + 1
    where o.id = (select locked_id from locked)
returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
`

func (q *Queries) Find(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, find, id)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
