// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find.sql

package postgres

import (
	"context"

	"uuid"
)

const find = `-- name: Find :one
select id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_by, last_error, created_at, updated_at, processed_at from dbtx.outbox where id = $1
`

func (q *Queries) Find(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, find, id)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return &i, err
}
