// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load.sql

package postgres

import (
	"context"
)

const load = `-- name: Load :one
  select id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
    from dbtx.outbox
   where (max_retry = 0 or retry_count < max_retry)
     and visible_at <= clock_timestamp()
order by id
   limit 1
     for update SKIP LOCKED
`

func (q *Queries) Load(ctx context.Context) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, load)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
