// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"encoding/json"
	"time"

	"uuid"
)

type DbtxOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	AggregateType string
	Type          string
	Payload       json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastError     string
	MaxRetry      int32
	RetryCount    int32
	VisibleAt     time.Time
}
