// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"

	"uuid"
)

type DbtxOutbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       json.RawMessage
	Status        string
	Attempts      int32
	MaxAttempts   int32
	AvailableAt   time.Time
	LockedBy      sql.NullString
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ProcessedAt   sql.NullTime
}
