// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nack.sql

package postgres

import (
	"context"

	"uuid"
)

const nack = `-- name: Nack :one
   update dbtx.outbox
      set last_error = $1,
          retry_count = retry_count + 1,
          -- Emulate DLQ by setting max retry to -1 (no longer retryable).
          max_retry = case when $2::boolean then -1 else max_retry end,
          visible_at = clock_timestamp() + $3::bigint * interval '1 microsecond',
          updated_at = clock_timestamp()
    where id = $4
returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
`

type NackParams struct {
	LastError string
	Dead      bool
	DelayUs   int64
	ID        uuid.UUID
}

func (q *Queries) Nack(ctx context.Context, arg NackParams) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, nack,
		arg.LastError,
		arg.Dead,
		arg.DelayUs,
		arg.ID,
	)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
