// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nack.sql

package postgres

import (
	"context"
	"database/sql"

	"uuid"
)

const nack = `-- name: Nack :execrows
update dbtx.outbox
   set status = case when $1::bool then 'dead' else 'pending' end,
       available_at = now()
     + interval '1 second' * $2::float8,
       locked_by = null,
       last_error = $3,
       updated_at = now()
 where id = $4
   and locked_by = $5
   and status = 'processing'
`

type NackParams struct {
	Dead         bool
	DelaySeconds float64
	LastError    sql.NullString
	ID           uuid.UUID
	LockedBy     sql.NullString
}

func (q *Queries) Nack(ctx context.Context, arg NackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, nack,
		arg.Dead,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.LockedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
