// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poll.sql

package postgres

import (
	"context"
	"database/sql"
)

const poll = `-- name: Poll :many
with next as (
    select id
      from dbtx.outbox
     where status in ('pending', 'processing')
       and available_at <= now()
       and attempts < max_attempts
  order by available_at, id
     limit $3
       for update skip locked
)
   update dbtx.outbox o
      set status = 'processing',
          locked_by = $1,
          updated_at = now(),
          available_at = now()
        + interval '1 second' * $2::float8,
          attempts = o.attempts + 1
     from next
    where o.id = next.id
returning o.id, o.aggregate_type, o.aggregate_id, o.event_type, o.payload, o.status, o.attempts, o.max_attempts, o.available_at, o.locked_by, o.last_error, o.created_at, o.updated_at, o.processed_at
`

type PollParams struct {
	LockedBy     sql.NullString
	LeaseSeconds float64
	BatchSize    int32
}

func (q *Queries) Poll(ctx context.Context, arg PollParams) ([]*DbtxOutbox, error) {
	rows, err := q.db.QueryContext(ctx, poll, arg.LockedBy, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxOutbox{}
	for rows.Next() {
		var i DbtxOutbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
