// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package postgres

import (
	"context"
	"time"
)

const purge = `-- name: Purge :execrows
delete from dbtx.outbox where status = $1 and updated_at < $2
`

type PurgeParams struct {
	Status    DbtxOutboxStatus
	UpdatedAt time.Time
}

func (q *Queries) Purge(ctx context.Context, arg PurgeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purge, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
