// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"uuid"
)

type Querier interface {
	Count(ctx context.Context) (int64, error)
	CountDLQ(ctx context.Context) (int64, error)
	Delete(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error)
	Dequeue(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error)
	DequeueFIFO(ctx context.Context) (*DbtxOutbox, error)
	Enqueue(ctx context.Context, arg EnqueueParams) (uuid.UUID, error)
	EnqueueDLQ(ctx context.Context, id uuid.UUID) (*DbtxOutboxDlq, error)
	Requeue(ctx context.Context, arg RequeueParams) (*DbtxOutbox, error)
}

var _ Querier = (*Queries)(nil)
