// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
	"time"

	"uuid"
)

type Querier interface {
	Count(ctx context.Context) (int64, error)
	Create(ctx context.Context, arg CreateParams) (*DbtxOutbox, error)
	Delete(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error)
	Exists(ctx context.Context, id uuid.UUID) (bool, error)
	Find(ctx context.Context, id uuid.UUID) (*DbtxOutbox, error)
	ListDead(ctx context.Context, maxRows int32) ([]*DbtxOutbox, error)
	Load(ctx context.Context) (*DbtxOutbox, error)
	Nack(ctx context.Context, arg NackParams) (*DbtxOutbox, error)
	PurgeDead(ctx context.Context, before time.Time) (int64, error)
	Requeue(ctx context.Context, arg RequeueParams) (*DbtxOutbox, error)
}

var _ Querier = (*Queries)(nil)
