// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requeue.sql

package postgres

import (
	"context"
	"database/sql"

	"uuid"
)

const requeue = `-- name: Requeue :one
   update dbtx.outbox
      set retry_at = $1, failure_reason = $2
    where id = $3
returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, failure_reason, retry_at, retry_count, run_at
`

type RequeueParams struct {
	RetryAt       sql.NullTime
	FailureReason string
	ID            uuid.UUID
}

func (q *Queries) Requeue(ctx context.Context, arg RequeueParams) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, requeue, arg.RetryAt, arg.FailureReason, arg.ID)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureReason,
		&i.RetryAt,
		&i.RetryCount,
		&i.RunAt,
	)
	return &i, err
}
