// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requeue.sql

package postgres

import (
	"context"
	"time"

	"uuid"
)

const requeue = `-- name: Requeue :one
   update dbtx.outbox
      set last_error = $1,
          visible_at = $2,
          max_retry = coalesce(
            nullif($3::int, 0), dbtx.outbox.max_retry
          ),
          updated_at = clock_timestamp()
    where id = $4
returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
`

type RequeueParams struct {
	LastError string
	VisibleAt time.Time
	MaxRetry  int32
	ID        uuid.UUID
}

func (q *Queries) Requeue(ctx context.Context, arg RequeueParams) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, requeue,
		arg.LastError,
		arg.VisibleAt,
		arg.MaxRetry,
		arg.ID,
	)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
