// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update.sql

package postgres

import (
	"context"
	"time"

	"uuid"
)

const update = `-- name: Update :one
   update dbtx.outbox
      set last_error = $1,
          visible_at = $2,
          max_retry = $3,
          retry_count = $4,
          updated_at = clock_timestamp()
    where id = $5
returning id, aggregate_id, aggregate_type, type, payload, created_at, updated_at, last_error, max_retry, retry_count, visible_at
`

type UpdateParams struct {
	LastError  string
	VisibleAt  time.Time
	MaxRetry   int32
	RetryCount int32
	ID         uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*DbtxOutbox, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.LastError,
		arg.VisibleAt,
		arg.MaxRetry,
		arg.RetryCount,
		arg.ID,
	)
	var i DbtxOutbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
		&i.MaxRetry,
		&i.RetryCount,
		&i.VisibleAt,
	)
	return &i, err
}
