// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup_expired.sql

package postgres

import (
	"context"
)

const cleanupExpired = `-- name: CleanupExpired :execrows
delete from dbtx.cache where expires_at is not null and expires_at <= now()
`

func (q *Queries) CleanupExpired(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupExpired)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
