// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare_and_delete.sql

package postgres

import (
	"context"
)

const compareAndDelete = `-- name: CompareAndDelete :one
delete from dbtx.cache where key = $1 and digest = $2 returning key, value, digest, created_at, updated_at, expires_at
`

type CompareAndDeleteParams struct {
	Key    string
	Digest string
}

func (q *Queries) CompareAndDelete(ctx context.Context, arg CompareAndDeleteParams) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, compareAndDelete, arg.Key, arg.Digest)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
