// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare_and_swap.sql

package postgres

import (
	"context"
	"encoding/json"
)

const compareAndSwap = `-- name: CompareAndSwap :one
update dbtx.cache set value = $1 where key = $2 and digest = $3 returning key, value, digest, created_at, updated_at, expires_at
`

type CompareAndSwapParams struct {
	Value  json.RawMessage
	Key    string
	Digest string
}

func (q *Queries) CompareAndSwap(ctx context.Context, arg CompareAndSwapParams) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, compareAndSwap, arg.Value, arg.Key, arg.Digest)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
