// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package postgres

import (
	"context"
)

const delete = `-- name: Delete :one
with expired as (
  delete from dbtx.cache where key = $1 and expires_at <= statement_timestamp() returning key
)
   delete
     from dbtx.cache
    where dbtx.cache.key = $1
      and not exists (select 1 from expired)
returning key, value, lease, created_at, updated_at, expires_at
`

// Deletes leased rows too, so that invalidating a key also discards any
// value that is being computed for it.
func (q *Queries) Delete(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, delete, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Lease,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
