// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_expired.sql

package postgres

import (
	"context"
)

const deleteExpired = `-- name: DeleteExpired :one
   delete
     from dbtx.cache
    where key = $1
      and expires_at is not null
      and expires_at <= now()
returning key, value, digest, created_at, updated_at, expires_at
`

func (q *Queries) DeleteExpired(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, deleteExpired, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
