// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package postgres

import (
	"context"
)

const delete = `-- name: Delete :one
delete from dbtx.cache where key = $1 returning key, value, digest, created_at, updated_at, expires_at
`

func (q *Queries) Delete(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, delete, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
