// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exists.sql

package postgres

import (
	"context"
)

const exists = `-- name: Exists :one
with expired as (
  delete from dbtx.cache where key = $1 and expires_at <= statement_timestamp() returning key
)
select exists
       (
         select 1
           from dbtx.cache
          where dbtx.cache.key = $1
            and lease is null
            and not exists (select 1 from expired)
       )
`

func (q *Queries) Exists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, exists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
