// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expire.sql

package postgres

import (
	"context"
	"database/sql"
)

const expire = `-- name: Expire :one
update dbtx.cache set expires_at = $1 where key = $2 returning key, value, digest, created_at, updated_at, expires_at
`

type ExpireParams struct {
	ExpiresAt sql.NullTime
	Key       string
}

func (q *Queries) Expire(ctx context.Context, arg ExpireParams) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, expire, arg.ExpiresAt, arg.Key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
