// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"
)

type DbtxCache struct {
	Key       string
	Value     json.RawMessage
	Digest    string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}
