// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package postgres

import (
	"context"
)

const purge = `-- name: Purge :execrows
delete from dbtx.cache where expires_at is not null and expires_at <= now()
`

func (q *Queries) Purge(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
