// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CleanupExpired(ctx context.Context) (int64, error)
	CompareAndDelete(ctx context.Context, arg CompareAndDeleteParams) (*DbtxCache, error)
	CompareAndSwap(ctx context.Context, arg CompareAndSwapParams) (*DbtxCache, error)
	Delete(ctx context.Context, key string) (*DbtxCache, error)
	DeleteExpired(ctx context.Context, key string) (*DbtxCache, error)
	Expire(ctx context.Context, arg ExpireParams) (*DbtxCache, error)
	Load(ctx context.Context, key string) (*DbtxCache, error)
	Store(ctx context.Context, arg StoreParams) (*DbtxCache, error)
	StoreOnce(ctx context.Context, arg StoreOnceParams) (*DbtxCache, error)
	TTL(ctx context.Context, key string) (*DbtxCache, error)
}

var _ Querier = (*Queries)(nil)
