// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const compareAndDelete = `-- name: CompareAndDelete :execrows
delete
  from dbtx.cache
 where key = $1
   and (digest = $2 or (expires_at is not null and expires_at <= now()))
`

type CompareAndDeleteParams struct {
	Key    string
	Digest string
}

func (q *Queries) CompareAndDelete(ctx context.Context, arg CompareAndDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndDelete, arg.Key, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const compareAndSwap = `-- name: CompareAndSwap :execrows
update dbtx.cache set value = $1 where key = $2 and digest = $3
`

type CompareAndSwapParams struct {
	Value  json.RawMessage
	Key    string
	Digest string
}

func (q *Queries) CompareAndSwap(ctx context.Context, arg CompareAndSwapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndSwap, arg.Value, arg.Key, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const delete = `-- name: Delete :one
delete from dbtx.cache where key = $1 returning key, value, digest, created_at, updated_at, expires_at
`

func (q *Queries) Delete(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, delete, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const deleteExpired = `-- name: DeleteExpired :execrows
   delete
     from dbtx.cache
    where key = $1
      and expires_at is not null
      and expires_at <= now()
returning key, value, digest, created_at, updated_at, expires_at
`

func (q *Queries) DeleteExpired(ctx context.Context, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpired, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expire = `-- name: Expire :exec
update dbtx.cache set expires_at = $1 where key = $2
`

type ExpireParams struct {
	ExpiresAt sql.NullTime
	Key       string
}

func (q *Queries) Expire(ctx context.Context, arg ExpireParams) error {
	_, err := q.db.ExecContext(ctx, expire, arg.ExpiresAt, arg.Key)
	return err
}

const load = `-- name: Load :one
select key, value, digest, created_at, updated_at, expires_at from dbtx.cache where key = $1 for update
`

func (q *Queries) Load(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, load, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const store = `-- name: Store :one
insert into dbtx.cache(key, value, digest, expires_at)
     values ($1, $2, $3, $4)
on conflict (key) do
     update
        set value = EXCLUDED.value, digest = EXCLUDED.digest, expires_at = EXCLUDED.expires_at
  returning key, value, digest, created_at, updated_at, expires_at
`

type StoreParams struct {
	Key       string
	Value     json.RawMessage
	Digest    string
	ExpiresAt sql.NullTime
}

func (q *Queries) Store(ctx context.Context, arg StoreParams) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, store,
		arg.Key,
		arg.Value,
		arg.Digest,
		arg.ExpiresAt,
	)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
