// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CompareAndDelete(ctx context.Context, arg CompareAndDeleteParams) (*DbtxLiveCache, error)
	CompareAndSwap(ctx context.Context, arg CompareAndSwapParams) (*DbtxLiveCache, error)
	Delete(ctx context.Context, key string) (*DbtxLiveCache, error)
	Expire(ctx context.Context, arg ExpireParams) (*DbtxLiveCache, error)
	Load(ctx context.Context, key string) (*DbtxLiveCache, error)
	Purge(ctx context.Context) (int64, error)
	Store(ctx context.Context, arg StoreParams) (*DbtxLiveCache, error)
	StoreOnce(ctx context.Context, arg StoreOnceParams) (*DbtxLiveCache, error)
}

var _ Querier = (*Queries)(nil)
