// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const store = `-- name: Store :one
insert into dbtx.cache(key, value, digest, expires_at)
     values ($1, $2, $3, $4)
on conflict (key) do
     update
        set value = EXCLUDED.value, digest = EXCLUDED.digest, expires_at = EXCLUDED.expires_at
  returning key, value, digest, created_at, updated_at, expires_at
`

type StoreParams struct {
	Key       string
	Value     json.RawMessage
	Digest    string
	ExpiresAt sql.NullTime
}

func (q *Queries) Store(ctx context.Context, arg StoreParams) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, store,
		arg.Key,
		arg.Value,
		arg.Digest,
		arg.ExpiresAt,
	)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
