// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_once.sql

package postgres

import (
	"context"
	"database/sql"

	"encoding/json/jsontext"
)

const storeOnce = `-- name: StoreOnce :execrows
insert into dbtx.cache as c(key, value, expires_at)
     values ($1, $2, statement_timestamp() + $3::bigint * interval '1 microsecond')
on conflict (key) do
     update
        set value = excluded.value,
            lease = null,
            expires_at = excluded.expires_at,
            created_at = statement_timestamp(),
            updated_at = statement_timestamp()
      where c.expires_at is not null
        and c.expires_at <= statement_timestamp()
`

type StoreOnceParams struct {
	Key   string
	Value jsontext.Value
	Ttl   sql.NullInt64
}

// Inserts the value unless a live row (including a lease placeholder) exists.
// An expired row is overwritten in place, since a sibling CTE deleting it would
// not be visible to the insert's conflict check.
func (q *Queries) StoreOnce(ctx context.Context, arg StoreOnceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, storeOnce, arg.Key, arg.Value, arg.Ttl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
