// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_once.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const storeOnce = `-- name: StoreOnce :one
insert into dbtx.live_cache(key, value, digest, expires_at)
     values ($1, $2, $3, $4)
on conflict (key) do
     update
        set value = $2, digest = $3, expires_at = $4
      where dbtx.live_cache.expires_at is not null
        and dbtx.live_cache.expires_at < now()
  returning key, value, digest, created_at, updated_at, expires_at
`

type StoreOnceParams struct {
	Key       string
	Value     json.RawMessage
	Digest    string
	ExpiresAt sql.NullTime
}

func (q *Queries) StoreOnce(ctx context.Context, arg StoreOnceParams) (*DbtxLiveCache, error) {
	row := q.db.QueryRowContext(ctx, storeOnce,
		arg.Key,
		arg.Value,
		arg.Digest,
		arg.ExpiresAt,
	)
	var i DbtxLiveCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
