// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ttl.sql

package postgres

import (
	"context"
)

const tTL = `-- name: TTL :one
select key, value, digest, created_at, updated_at, expires_at from dbtx.cache where key = $1
`

func (q *Queries) TTL(ctx context.Context, key string) (*DbtxCache, error) {
	row := q.db.QueryRowContext(ctx, tTL, key)
	var i DbtxCache
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
