// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"

	"uuid"
)

type DbtxBanditArm struct {
	ExperimentID uuid.UUID
	ArmKey       string
	Label        string
	Ordinal      int32
}

type DbtxBanditDecision struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ArmKey      string
	Sequence    int64
	RequestKey  string
	Diagnostics json.RawMessage
	CreatedAt   time.Time
}

type DbtxBanditExperiment struct {
	ID         uuid.UUID
	Definition json.RawMessage
	CreatedAt  time.Time
}

type DbtxBanditFeedback struct {
	DecisionID uuid.UUID
	Success    bool
	ObservedAt time.Time
}

type DbtxBanditRun struct {
	ID           uuid.UUID
	ExperimentID uuid.UUID
	Definition   json.RawMessage
	Sequence     int64
	Status       string
	CreatedAt    time.Time
	ClosedAt     sql.NullTime
}

type DbtxBanditStatistic struct {
	RunID        uuid.UUID
	ExperimentID uuid.UUID
	ArmKey       string
	Selections   int64
	Observations int64
	Successes    int64
}
