// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"uuid"
)

const advance = `-- name: Advance :exec
UPDATE dbtx.bandit_runs SET sequence=sequence+1 WHERE id=$1
`

func (q *Queries) Advance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, advance, id)
	return err
}

const closeRun = `-- name: CloseRun :exec
UPDATE dbtx.bandit_runs SET status='closed',closed_at=COALESCE(closed_at,clock_timestamp()) WHERE id=$1
`

func (q *Queries) CloseRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, closeRun, id)
	return err
}

const createArm = `-- name: CreateArm :exec
INSERT INTO dbtx.bandit_arms (experiment_id,arm_key,label,ordinal) VALUES ($1,$2,$3,$4)
`

type CreateArmParams struct {
	ExperimentID uuid.UUID
	ArmKey       string
	Label        string
	Ordinal      int32
}

func (q *Queries) CreateArm(ctx context.Context, arg CreateArmParams) error {
	_, err := q.db.ExecContext(ctx, createArm,
		arg.ExperimentID,
		arg.ArmKey,
		arg.Label,
		arg.Ordinal,
	)
	return err
}

const createDecision = `-- name: CreateDecision :one
INSERT INTO dbtx.bandit_decisions (id,run_id,arm_key,sequence,request_key,diagnostics) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, run_id, arm_key, sequence, request_key, diagnostics, created_at
`

type CreateDecisionParams struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ArmKey      string
	Sequence    int64
	RequestKey  string
	Diagnostics json.RawMessage
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (DbtxBanditDecision, error) {
	row := q.db.QueryRowContext(ctx, createDecision,
		arg.ID,
		arg.RunID,
		arg.ArmKey,
		arg.Sequence,
		arg.RequestKey,
		arg.Diagnostics,
	)
	var i DbtxBanditDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArmKey,
		&i.Sequence,
		&i.RequestKey,
		&i.Diagnostics,
		&i.CreatedAt,
	)
	return i, err
}

const createExperiment = `-- name: CreateExperiment :one
INSERT INTO dbtx.bandit_experiments (id, definition) VALUES ($1,$2) RETURNING id, definition, created_at
`

type CreateExperimentParams struct {
	ID         uuid.UUID
	Definition json.RawMessage
}

func (q *Queries) CreateExperiment(ctx context.Context, arg CreateExperimentParams) (DbtxBanditExperiment, error) {
	row := q.db.QueryRowContext(ctx, createExperiment, arg.ID, arg.Definition)
	var i DbtxBanditExperiment
	err := row.Scan(&i.ID, &i.Definition, &i.CreatedAt)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :exec
INSERT INTO dbtx.bandit_feedback (decision_id,success) VALUES ($1,$2)
`

type CreateFeedbackParams struct {
	DecisionID uuid.UUID
	Success    bool
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, createFeedback, arg.DecisionID, arg.Success)
	return err
}

const createRun = `-- name: CreateRun :one
INSERT INTO dbtx.bandit_runs (id,experiment_id,definition) VALUES ($1,$2,$3) RETURNING id, experiment_id, definition, sequence, status, created_at, closed_at
`

type CreateRunParams struct {
	ID           uuid.UUID
	ExperimentID uuid.UUID
	Definition   json.RawMessage
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (DbtxBanditRun, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.ID, arg.ExperimentID, arg.Definition)
	var i DbtxBanditRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Definition,
		&i.Sequence,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createStatistics = `-- name: CreateStatistics :exec
INSERT INTO dbtx.bandit_statistics (run_id,experiment_id,arm_key) VALUES ($1,$2,$3)
`

type CreateStatisticsParams struct {
	RunID        uuid.UUID
	ExperimentID uuid.UUID
	ArmKey       string
}

func (q *Queries) CreateStatistics(ctx context.Context, arg CreateStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, createStatistics, arg.RunID, arg.ExperimentID, arg.ArmKey)
	return err
}

const decision = `-- name: Decision :one
SELECT d.id, d.run_id, d.arm_key, d.sequence, d.request_key, d.diagnostics, d.created_at,f.success,f.observed_at FROM dbtx.bandit_decisions d LEFT JOIN dbtx.bandit_feedback f ON f.decision_id=d.id WHERE d.id=$1
`

type DecisionRow struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ArmKey      string
	Sequence    int64
	RequestKey  string
	Diagnostics json.RawMessage
	CreatedAt   time.Time
	Success     sql.NullBool
	ObservedAt  sql.NullTime
}

func (q *Queries) Decision(ctx context.Context, id uuid.UUID) (DecisionRow, error) {
	row := q.db.QueryRowContext(ctx, decision, id)
	var i DecisionRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArmKey,
		&i.Sequence,
		&i.RequestKey,
		&i.Diagnostics,
		&i.CreatedAt,
		&i.Success,
		&i.ObservedAt,
	)
	return i, err
}

const decisionByKey = `-- name: DecisionByKey :one
SELECT d.id, d.run_id, d.arm_key, d.sequence, d.request_key, d.diagnostics, d.created_at,f.success,f.observed_at FROM dbtx.bandit_decisions d LEFT JOIN dbtx.bandit_feedback f ON f.decision_id=d.id WHERE d.run_id=$1 AND d.request_key=$2
`

type DecisionByKeyParams struct {
	RunID      uuid.UUID
	RequestKey string
}

type DecisionByKeyRow struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ArmKey      string
	Sequence    int64
	RequestKey  string
	Diagnostics json.RawMessage
	CreatedAt   time.Time
	Success     sql.NullBool
	ObservedAt  sql.NullTime
}

func (q *Queries) DecisionByKey(ctx context.Context, arg DecisionByKeyParams) (DecisionByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, decisionByKey, arg.RunID, arg.RequestKey)
	var i DecisionByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArmKey,
		&i.Sequence,
		&i.RequestKey,
		&i.Diagnostics,
		&i.CreatedAt,
		&i.Success,
		&i.ObservedAt,
	)
	return i, err
}

const experiment = `-- name: Experiment :one
SELECT id, definition, created_at FROM dbtx.bandit_experiments WHERE id=$1
`

func (q *Queries) Experiment(ctx context.Context, id uuid.UUID) (DbtxBanditExperiment, error) {
	row := q.db.QueryRowContext(ctx, experiment, id)
	var i DbtxBanditExperiment
	err := row.Scan(&i.ID, &i.Definition, &i.CreatedAt)
	return i, err
}

const experiments = `-- name: Experiments :many
SELECT id, definition, created_at FROM dbtx.bandit_experiments ORDER BY created_at DESC,id LIMIT $1 OFFSET $2
`

type ExperimentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) Experiments(ctx context.Context, arg ExperimentsParams) ([]DbtxBanditExperiment, error) {
	rows, err := q.db.QueryContext(ctx, experiments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DbtxBanditExperiment{}
	for rows.Next() {
		var i DbtxBanditExperiment
		if err := rows.Scan(&i.ID, &i.Definition, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishSimulation = `-- name: FinishSimulation :exec
UPDATE dbtx.bandit_runs SET sequence=$2,status='closed',closed_at=clock_timestamp() WHERE id=$1
`

type FinishSimulationParams struct {
	ID       uuid.UUID
	Sequence int64
}

func (q *Queries) FinishSimulation(ctx context.Context, arg FinishSimulationParams) error {
	_, err := q.db.ExecContext(ctx, finishSimulation, arg.ID, arg.Sequence)
	return err
}

const history = `-- name: History :many
SELECT d.id, d.run_id, d.arm_key, d.sequence, d.request_key, d.diagnostics, d.created_at,f.success,f.observed_at FROM dbtx.bandit_decisions d LEFT JOIN dbtx.bandit_feedback f ON f.decision_id=d.id WHERE d.run_id=$1 ORDER BY d.sequence LIMIT $2 OFFSET $3
`

type HistoryParams struct {
	RunID  uuid.UUID
	Limit  int32
	Offset int32
}

type HistoryRow struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ArmKey      string
	Sequence    int64
	RequestKey  string
	Diagnostics json.RawMessage
	CreatedAt   time.Time
	Success     sql.NullBool
	ObservedAt  sql.NullTime
}

func (q *Queries) History(ctx context.Context, arg HistoryParams) ([]HistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, history, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryRow{}
	for rows.Next() {
		var i HistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArmKey,
			&i.Sequence,
			&i.RequestKey,
			&i.Diagnostics,
			&i.CreatedAt,
			&i.Success,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRun = `-- name: LockRun :one
SELECT id, experiment_id, definition, sequence, status, created_at, closed_at FROM dbtx.bandit_runs WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRun(ctx context.Context, id uuid.UUID) (DbtxBanditRun, error) {
	row := q.db.QueryRowContext(ctx, lockRun, id)
	var i DbtxBanditRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Definition,
		&i.Sequence,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const observeArm = `-- name: ObserveArm :exec
UPDATE dbtx.bandit_statistics SET observations=observations+1,successes=successes+$1::bigint WHERE run_id=$2 AND arm_key=$3
`

type ObserveArmParams struct {
	Reward int64
	RunID  uuid.UUID
	ArmKey string
}

func (q *Queries) ObserveArm(ctx context.Context, arg ObserveArmParams) error {
	_, err := q.db.ExecContext(ctx, observeArm, arg.Reward, arg.RunID, arg.ArmKey)
	return err
}

const run = `-- name: Run :one
SELECT id, experiment_id, definition, sequence, status, created_at, closed_at FROM dbtx.bandit_runs WHERE id=$1
`

func (q *Queries) Run(ctx context.Context, id uuid.UUID) (DbtxBanditRun, error) {
	row := q.db.QueryRowContext(ctx, run, id)
	var i DbtxBanditRun
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.Definition,
		&i.Sequence,
		&i.Status,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const runs = `-- name: Runs :many
SELECT id, experiment_id, definition, sequence, status, created_at, closed_at FROM dbtx.bandit_runs WHERE experiment_id=$1 ORDER BY created_at DESC,id LIMIT $2 OFFSET $3
`

type RunsParams struct {
	ExperimentID uuid.UUID
	Limit        int32
	Offset       int32
}

func (q *Queries) Runs(ctx context.Context, arg RunsParams) ([]DbtxBanditRun, error) {
	rows, err := q.db.QueryContext(ctx, runs, arg.ExperimentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DbtxBanditRun{}
	for rows.Next() {
		var i DbtxBanditRun
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Definition,
			&i.Sequence,
			&i.Status,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStatistics = `-- name: SaveStatistics :exec
UPDATE dbtx.bandit_statistics SET selections=$3,observations=$4,successes=$5 WHERE run_id=$1 AND arm_key=$2
`

type SaveStatisticsParams struct {
	RunID        uuid.UUID
	ArmKey       string
	Selections   int64
	Observations int64
	Successes    int64
}

func (q *Queries) SaveStatistics(ctx context.Context, arg SaveStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, saveStatistics,
		arg.RunID,
		arg.ArmKey,
		arg.Selections,
		arg.Observations,
		arg.Successes,
	)
	return err
}

const selectArm = `-- name: SelectArm :exec
UPDATE dbtx.bandit_statistics SET selections=selections+1 WHERE run_id=$1 AND arm_key=$2
`

type SelectArmParams struct {
	RunID  uuid.UUID
	ArmKey string
}

func (q *Queries) SelectArm(ctx context.Context, arg SelectArmParams) error {
	_, err := q.db.ExecContext(ctx, selectArm, arg.RunID, arg.ArmKey)
	return err
}

const statistics = `-- name: Statistics :many
SELECT s.run_id, s.experiment_id, s.arm_key, s.selections, s.observations, s.successes,a.label,a.ordinal FROM dbtx.bandit_statistics s JOIN dbtx.bandit_arms a USING(experiment_id,arm_key) WHERE s.run_id=$1 ORDER BY a.ordinal
`

type StatisticsRow struct {
	RunID        uuid.UUID
	ExperimentID uuid.UUID
	ArmKey       string
	Selections   int64
	Observations int64
	Successes    int64
	Label        string
	Ordinal      int32
}

func (q *Queries) Statistics(ctx context.Context, runID uuid.UUID) ([]StatisticsRow, error) {
	rows, err := q.db.QueryContext(ctx, statistics, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatisticsRow{}
	for rows.Next() {
		var i StatisticsRow
		if err := rows.Scan(
			&i.RunID,
			&i.ExperimentID,
			&i.ArmKey,
			&i.Selections,
			&i.Observations,
			&i.Successes,
			&i.Label,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trajectory = `-- name: Trajectory :many
SELECT d.id,d.run_id,d.arm_key,d.sequence,d.request_key,d.created_at,f.success,f.observed_at FROM dbtx.bandit_decisions d LEFT JOIN dbtx.bandit_feedback f ON f.decision_id=d.id WHERE d.run_id=$1 ORDER BY d.sequence
`

type TrajectoryRow struct {
	ID         uuid.UUID
	RunID      uuid.UUID
	ArmKey     string
	Sequence   int64
	RequestKey string
	CreatedAt  time.Time
	Success    sql.NullBool
	ObservedAt sql.NullTime
}

func (q *Queries) Trajectory(ctx context.Context, runID uuid.UUID) ([]TrajectoryRow, error) {
	rows, err := q.db.QueryContext(ctx, trajectory, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrajectoryRow{}
	for rows.Next() {
		var i TrajectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArmKey,
			&i.Sequence,
			&i.RequestKey,
			&i.CreatedAt,
			&i.Success,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
