// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"

	"encoding/json/jsontext"
	"uuid"
)

type DbtxJob struct {
	ID             uuid.UUID
	IdempotencyKey string
	Request        jsontext.Value
	Response       jsontext.Value
	Status         string
	WorkerID       sql.NullString
	FencingToken   int64
	Attempts       int32
	MaxAttempts    int32
	Error          sql.NullString
	VisibleAt      time.Time
	ProcessedAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DbtxJobKey struct {
	IdempotencyKey string
	JobID          uuid.UUID
	RequestHash    []byte
	CreatedAt      time.Time
}

type DbtxJobsArchive struct {
	ID             uuid.UUID
	IdempotencyKey string
	Request        jsontext.Value
	Response       jsontext.Value
	Status         string
	WorkerID       sql.NullString
	FencingToken   int64
	Attempts       int32
	MaxAttempts    int32
	Error          sql.NullString
	VisibleAt      time.Time
	ProcessedAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
