// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"encoding/json/jsontext"
	"uuid"
)

const archiveOldJobs = `-- name: ArchiveOldJobs :one
WITH picked AS (
    SELECT id
    FROM dbtx.jobs
    WHERE status IN ('success', 'failed')
      AND updated_at < NOW() - (INTERVAL '1 second' * $1::float8)
    ORDER BY updated_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
),
moved AS (
    DELETE FROM dbtx.jobs j
    USING picked
    WHERE j.id = picked.id
    RETURNING j.id, j.idempotency_key, j.request, j.response, j.status, j.worker_id, j.fencing_token, j.attempts, j.max_attempts, j.error, j.visible_at, j.processed_at, j.created_at, j.updated_at
),
inserted AS (
    INSERT INTO dbtx.jobs_archive (
        id, idempotency_key, request, response, status, worker_id, fencing_token,
        attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
    )
    SELECT
        id, idempotency_key, request, response, status, worker_id, fencing_token,
        attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
    FROM moved
    RETURNING 1
)
SELECT COUNT(*) FROM inserted
`

type ArchiveOldJobsParams struct {
	RetentionSeconds float64
	BatchSize        int32
}

// -----------------------------------------------------------------------------
// Archive finished jobs in bounded batches. Call repeatedly until it returns 0.
// A single unbounded DELETE would hold locks, spike WAL and bloat the table.
// DELETE + INSERT happen in one statement/transaction, so a row is always in
// exactly one of jobs / jobs_archive. Columns are listed explicitly so a future
// ALTER TABLE on one table cannot silently misalign the copy.
func (q *Queries) ArchiveOldJobs(ctx context.Context, arg ArchiveOldJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, archiveOldJobs, arg.RetentionSeconds, arg.BatchSize)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const complete = `-- name: Complete :one
UPDATE dbtx.jobs
SET status       = 'success',
    response     = $1::jsonb,
    error        = NULL,
    worker_id    = NULL,
    visible_at   = clock_timestamp(),
    processed_at = clock_timestamp()
WHERE id            = $2
  AND status        = 'running'
  AND fencing_token = $3
  AND worker_id     = $4::text
RETURNING id, idempotency_key, request, response, status, worker_id, fencing_token, attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
`

type CompleteParams struct {
	Response     jsontext.Value
	ID           uuid.UUID
	FencingToken int64
	WorkerID     string
}

// -----------------------------------------------------------------------------
// Terminal success. (worker_id guard is redundant with the per-claim token but
// kept as defense in depth.)
func (q *Queries) Complete(ctx context.Context, arg CompleteParams) (*DbtxJob, error) {
	row := q.db.QueryRowContext(ctx, complete,
		arg.Response,
		arg.ID,
		arg.FencingToken,
		arg.WorkerID,
	)
	var i DbtxJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Request,
		&i.Response,
		&i.Status,
		&i.WorkerID,
		&i.FencingToken,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.VisibleAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const create = `-- name: Create :one
SELECT
  o_id::uuid as id,
  o_status::dbtx.job_status as status,
  o_response::jsonb as response,
  coalesce(o_error, '')::text as error,
  o_payload_matches::bool as payload_matches,
  o_created::bool as created
FROM dbtx.create_job(
    $1::text,
    $2::jsonb,
    $3::float8,
    $4::int
)
`

type CreateParams struct {
	IdempotencyKey string
	Request        jsontext.Value
	DelaySeconds   float64
	MaxAttempts    int32
}

type CreateRow struct {
	ID             uuid.UUID
	Status         string
	Response       jsontext.Value
	Error          string
	PayloadMatches bool
	Created        bool
}

// (sqlc: verify it handles OUT parameters; otherwise declare the function as
//
//	RETURNS TABLE(...) or call it from plain SQL.)
func (q *Queries) Create(ctx context.Context, arg CreateParams) (*CreateRow, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.IdempotencyKey,
		arg.Request,
		arg.DelaySeconds,
		arg.MaxAttempts,
	)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Response,
		&i.Error,
		&i.PayloadMatches,
		&i.Created,
	)
	return &i, err
}

const fail = `-- name: Fail :one
UPDATE dbtx.jobs
SET status       = 'failed',
    error        = $1::text,
    worker_id    = NULL,
    visible_at   = clock_timestamp(),
    processed_at = clock_timestamp()
WHERE id            = $2
  AND status        = 'running'
  AND fencing_token = $3
  AND worker_id     = $4::text
RETURNING id, idempotency_key, request, response, status, worker_id, fencing_token, attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
`

type FailParams struct {
	Error        string
	ID           uuid.UUID
	FencingToken int64
	WorkerID     string
}

// -----------------------------------------------------------------------------
// Terminal failure (non-retryable). Sets processed_at to satisfy the CHECK.
func (q *Queries) Fail(ctx context.Context, arg FailParams) (*DbtxJob, error) {
	row := q.db.QueryRowContext(ctx, fail,
		arg.Error,
		arg.ID,
		arg.FencingToken,
		arg.WorkerID,
	)
	var i DbtxJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Request,
		&i.Response,
		&i.Status,
		&i.WorkerID,
		&i.FencingToken,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.VisibleAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findAvailableJobs = `-- name: FindAvailableJobs :many
WITH picked AS MATERIALIZED (
    SELECT sub.id
    FROM dbtx.jobs sub
    WHERE sub.status IN ('queued', 'running', 'error')   -- 'running' here = expired lease
      AND sub.visible_at <= NOW()
      AND sub.attempts < sub.max_attempts
    ORDER BY sub.visible_at
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
)
UPDATE dbtx.jobs
SET status        = 'running',
    fencing_token = jobs.fencing_token + 1,   -- new owner => older tokens are now invalid
    worker_id     = $1::text,
    visible_at    = clock_timestamp() + (INTERVAL '1 second' * $2::float8),
    attempts      = jobs.attempts + 1
    -- error is intentionally NOT cleared: if this attempt's worker crashes, the
    -- previous failure reason is still available. Complete clears it on success.
FROM picked
WHERE jobs.id = picked.id
RETURNING jobs.id, jobs.idempotency_key, jobs.request, jobs.response, jobs.status, jobs.worker_id, jobs.fencing_token, jobs.attempts, jobs.max_attempts, jobs.error, jobs.visible_at, jobs.processed_at, jobs.created_at, jobs.updated_at
`

type FindAvailableJobsParams struct {
	WorkerID     string
	LeaseSeconds float64
	Limit        int32
}

// -----------------------------------------------------------------------------
// Claim
// -----------------------------------------------------------------------------
// Time handling: filters use NOW() because it is STABLE and can drive the
// partial index scan (a volatile clock_timestamp() in a WHERE clause cannot be
// used as an index condition and would force filtering many future rows).
// Lease writes use clock_timestamp() so a long transaction cannot shorten them.
//
// ORDER BY visible_at gives oldest-due-first fairness and uses the partial
// index. MATERIALIZED stops the planner from folding the locking subquery
// into the outer UPDATE, which could change which rows get locked.
func (q *Queries) FindAvailableJobs(ctx context.Context, arg FindAvailableJobsParams) ([]*DbtxJob, error) {
	rows, err := q.db.QueryContext(ctx, findAvailableJobs, arg.WorkerID, arg.LeaseSeconds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DbtxJob{}
	for rows.Next() {
		var i DbtxJob
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Request,
			&i.Response,
			&i.Status,
			&i.WorkerID,
			&i.FencingToken,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.VisibleAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heartbeat = `-- name: Heartbeat :one
UPDATE dbtx.jobs
SET visible_at = clock_timestamp() + (INTERVAL '1 second' * $1::float8)
WHERE id            = $2
  AND status        = 'running'
  AND fencing_token = $3
  AND worker_id     = $4::text
RETURNING id, idempotency_key, request, response, status, worker_id, fencing_token, attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
`

type HeartbeatParams struct {
	LeaseSeconds float64
	ID           uuid.UUID
	FencingToken int64
	WorkerID     string
}

// -----------------------------------------------------------------------------
// Lease renewal. Zero rows => lease lost (expired and reclaimed, or finished).
// A worker whose lease merely expired but was NOT yet reclaimed can still
// heartbeat/complete: the token is unchanged, so that is correct.
func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) (*DbtxJob, error) {
	row := q.db.QueryRowContext(ctx, heartbeat,
		arg.LeaseSeconds,
		arg.ID,
		arg.FencingToken,
		arg.WorkerID,
	)
	var i DbtxJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Request,
		&i.Response,
		&i.Status,
		&i.WorkerID,
		&i.FencingToken,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.VisibleAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const purgeOldJobKeys = `-- name: PurgeOldJobKeys :execrows
DELETE FROM dbtx.job_keys
WHERE idempotency_key IN (
    SELECT k.idempotency_key
    FROM dbtx.job_keys k
    WHERE k.created_at < NOW() - (INTERVAL '1 second' * $1::float8)
      AND NOT EXISTS (SELECT 1 FROM dbtx.jobs j WHERE j.id = k.job_id)  -- never orphan a live job
    ORDER BY k.created_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
`

type PurgeOldJobKeysParams struct {
	KeyTtlSeconds float64
	BatchSize     int32
}

// -----------------------------------------------------------------------------
// Expire idempotency keys after the window in which clients may retry.
// Keep this window LONGER than job retention. After a key is purged, the same
// key creates a new job, which is the intended end of the idempotency window.
func (q *Queries) PurgeOldJobKeys(ctx context.Context, arg PurgeOldJobKeysParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldJobKeys, arg.KeyTtlSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reapExhausted = `-- name: ReapExhausted :execrows
UPDATE dbtx.jobs
SET status       = 'failed',
    worker_id    = NULL,
    processed_at = clock_timestamp(),
    error        = COALESCE(error, 'lease expired; max attempts exceeded')
WHERE status IN ('running', 'error')
  AND visible_at <= NOW() - (INTERVAL '1 second' * $1::float8)
  AND attempts >= max_attempts
`

// -----------------------------------------------------------------------------
// Reaper: a worker that crashes on its LAST attempt leaves a 'running' row with
// an expired lease and attempts = max_attempts. The claim query skips it
// (attempts < max_attempts), so without this it would be stuck forever and
// would also never be archived. Run periodically (e.g. every minute).
//
// A worker whose lease merely expired can still complete (see Heartbeat), so
// the lease must have expired grace_seconds ago, giving that worker time to
// record its outcome.
func (q *Queries) ReapExhausted(ctx context.Context, graceSeconds float64) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapExhausted, graceSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retry = `-- name: Retry :one
UPDATE dbtx.jobs
SET status       = CASE WHEN attempts >= max_attempts
                        THEN 'failed'::dbtx.job_status
                        ELSE 'error'::dbtx.job_status END,
    visible_at   = clock_timestamp() + (INTERVAL '1 second' * $1::float8),
    processed_at = CASE WHEN attempts >= max_attempts THEN clock_timestamp() END,
    worker_id    = NULL,
    error        = $2::text
WHERE id            = $3
  AND status        = 'running'
  AND fencing_token = $4
  AND worker_id     = $5::text
RETURNING id, idempotency_key, request, response, status, worker_id, fencing_token, attempts, max_attempts, error, visible_at, processed_at, created_at, updated_at
`

type RetryParams struct {
	BackoffSeconds float64
	Error          string
	ID             uuid.UUID
	FencingToken   int64
	WorkerID       string
}

// -----------------------------------------------------------------------------
// Retry with backoff. When attempts are exhausted the job becomes terminal
// ('failed') instead of sitting in 'error' forever (the claim query would
// never pick it up again). RHS column references see the OLD row.
func (q *Queries) Retry(ctx context.Context, arg RetryParams) (*DbtxJob, error) {
	row := q.db.QueryRowContext(ctx, retry,
		arg.BackoffSeconds,
		arg.Error,
		arg.ID,
		arg.FencingToken,
		arg.WorkerID,
	)
	var i DbtxJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Request,
		&i.Response,
		&i.Status,
		&i.WorkerID,
		&i.FencingToken,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.VisibleAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
