// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	// -----------------------------------------------------------------------------
	// Archive finished jobs in bounded batches. Call repeatedly until it returns 0.
	// A single unbounded DELETE would hold locks, spike WAL and bloat the table.
	// DELETE + INSERT happen in one statement/transaction, so a row is always in
	// exactly one of jobs / jobs_archive. Columns are listed explicitly so a future
	// ALTER TABLE on one table cannot silently misalign the copy.
	ArchiveOldJobs(ctx context.Context, arg ArchiveOldJobsParams) (int64, error)
	// -----------------------------------------------------------------------------
	// Terminal success. (worker_id guard is redundant with the per-claim token but
	// kept as defense in depth.)
	Complete(ctx context.Context, arg CompleteParams) (*DbtxJob, error)
	// (sqlc: verify it handles OUT parameters; otherwise declare the function as
	//  RETURNS TABLE(...) or call it from plain SQL.)
	Create(ctx context.Context, arg CreateParams) (*CreateRow, error)
	// -----------------------------------------------------------------------------
	// Terminal failure (non-retryable). Sets processed_at to satisfy the CHECK.
	Fail(ctx context.Context, arg FailParams) (*DbtxJob, error)
	// -----------------------------------------------------------------------------
	// Claim
	// -----------------------------------------------------------------------------
	// Time handling: filters use NOW() because it is STABLE and can drive the
	// partial index scan (a volatile clock_timestamp() in a WHERE clause cannot be
	// used as an index condition and would force filtering many future rows).
	// Lease writes use clock_timestamp() so a long transaction cannot shorten them.
	//
	// ORDER BY visible_at gives oldest-due-first fairness and uses the partial
	// index. MATERIALIZED stops the planner from folding the locking subquery
	// into the outer UPDATE, which could change which rows get locked.
	FindAvailableJobs(ctx context.Context, arg FindAvailableJobsParams) ([]*DbtxJob, error)
	// -----------------------------------------------------------------------------
	// Lease renewal. Zero rows => lease lost (expired and reclaimed, or finished).
	// A worker whose lease merely expired but was NOT yet reclaimed can still
	// heartbeat/complete: the token is unchanged, so that is correct.
	Heartbeat(ctx context.Context, arg HeartbeatParams) (*DbtxJob, error)
	// -----------------------------------------------------------------------------
	// Expire idempotency keys after the window in which clients may retry.
	// Keep this window LONGER than job retention. After a key is purged, the same
	// key creates a new job, which is the intended end of the idempotency window.
	PurgeOldJobKeys(ctx context.Context, arg PurgeOldJobKeysParams) (int64, error)
	// -----------------------------------------------------------------------------
	// Reaper: a worker that crashes on its LAST attempt leaves a 'running' row with
	// an expired lease and attempts = max_attempts. The claim query skips it
	// (attempts < max_attempts), so without this it would be stuck forever and
	// would also never be archived. Run periodically (e.g. every minute).
	//
	// A worker whose lease merely expired can still complete (see Heartbeat), so
	// the lease must have expired grace_seconds ago, giving that worker time to
	// record its outcome.
	ReapExhausted(ctx context.Context, graceSeconds float64) (int64, error)
	// -----------------------------------------------------------------------------
	// Retry with backoff. When attempts are exhausted the job becomes terminal
	// ('failed') instead of sitting in 'error' forever (the claim query would
	// never pick it up again). RHS column references see the OLD row.
	Retry(ctx context.Context, arg RetryParams) (*DbtxJob, error)
}

var _ Querier = (*Queries)(nil)
